package com.example.ui.theme

import androidx.compose.ui.graphics.Color

// 8 Master Terminal Themes
data class TerminalThemeConfig(
    val id: String,
    val name: String,
    val description: String,
    val price: Int,
    val primary: Color,
    val primaryDim: Color,
    val secondary: Color,
    val tertiary: Color,
    val bgDark: Color,
    val surface1: Color,
    val surface2: Color,
    val surface3: Color,
    val textLight: Color,
    val textGray: Color,
    val error: Color,
    val success: Color
)

val ThemeList = listOf(
    TerminalThemeConfig(
        id = "default",
        name = "Blood Terminal",
        description = "Standard dystopian red-orange survival interface",
        price = 0,
        primary = Color(0xFFFF3B30),
        primaryDim = Color(0x33FF3B30),
        secondary = Color(0xFFFF9500),
        tertiary = Color(0xFFFFCC00),
        bgDark = Color(0xFF0A0A0C),
        surface1 = Color(0xFF151517),
        surface2 = Color(0xFF1E1E21),
        surface3 = Color(0xFF2A2A2E),
        textLight = Color(0xFFF5F5F7),
        textGray = Color(0xFF9A9AA2),
        error = Color(0xFFFF453A),
        success = Color(0xFF34C759)
    ),
    TerminalThemeConfig(
        id = "retro_green",
        name = "Matrix Phosphor",
        description = "Classic monochrome green cathode ray CRT monitor",
        price = 200,
        primary = Color(0xFF00FF66),
        primaryDim = Color(0x3300FF66),
        secondary = Color(0xFF39FF14),
        tertiary = Color(0xFF76FF03),
        bgDark = Color(0xFF041006),
        surface1 = Color(0xFF091C0E),
        surface2 = Color(0xFF0F2C18),
        surface3 = Color(0xFF183D24),
        textLight = Color(0xFFE8FFE8),
        textGray = Color(0xFF66BB6A),
        error = Color(0xFFFF5252),
        success = Color(0xFF00E676)
    ),
    TerminalThemeConfig(
        id = "amber_alert",
        name = "Amber Alert",
        description = "Industrial emergency amber surveillance terminal",
        price = 250,
        primary = Color(0xFFFFB300),
        primaryDim = Color(0x33FFB300),
        secondary = Color(0xFFFF8800),
        tertiary = Color(0xFFFFD54F),
        bgDark = Color(0xFF120C03),
        surface1 = Color(0xFF1D1407),
        surface2 = Color(0xFF2B1F0D),
        surface3 = Color(0xFF3B2C16),
        textLight = Color(0xFFFFF3E0),
        textGray = Color(0xFFFFA726),
        error = Color(0xFFFF3D00),
        success = Color(0xFF66BB6A)
    ),
    TerminalThemeConfig(
        id = "ghost_white",
        name = "Ghost Monolith",
        description = "High-contrast tactical grayscale HUD",
        price = 300,
        primary = Color(0xFFECEFF1),
        primaryDim = Color(0x33ECEFF1),
        secondary = Color(0xFFCFD8DC),
        tertiary = Color(0xFF90A4AE),
        bgDark = Color(0xFF0B0C0E),
        surface1 = Color(0xFF16181C),
        surface2 = Color(0xFF22252B),
        surface3 = Color(0xFF2F343C),
        textLight = Color(0xFFFFFFFF),
        textGray = Color(0xFF9E9E9E),
        error = Color(0xFFEF5350),
        success = Color(0xFF81C784)
    ),
    TerminalThemeConfig(
        id = "cyber_blue",
        name = "Cyber Cyan",
        description = "High-frequency sub-orbital network uplink",
        price = 350,
        primary = Color(0xFF00F0FF),
        primaryDim = Color(0x3300F0FF),
        secondary = Color(0xFF0077FE),
        tertiary = Color(0xFF80D8FF),
        bgDark = Color(0xFF030B14),
        surface1 = Color(0xFF081726),
        surface2 = Color(0xFF0F263D),
        surface3 = Color(0xFF183856),
        textLight = Color(0xFFE0F7FA),
        textGray = Color(0xFF4FC3F7),
        error = Color(0xFFFF5252),
        success = Color(0xFF00E5FF)
    ),
    TerminalThemeConfig(
        id = "blood_moon",
        name = "Blood Moon",
        description = "Crimson eclipse stealth operative HUD",
        price = 400,
        primary = Color(0xFFFF1744),
        primaryDim = Color(0x33FF1744),
        secondary = Color(0xFFD50000),
        tertiary = Color(0xFFFF5252),
        bgDark = Color(0xFF120306),
        surface1 = Color(0xFF1F070C),
        surface2 = Color(0xFF2F0D15),
        surface3 = Color(0xFF42141F),
        textLight = Color(0xFFFFEBEE),
        textGray = Color(0xFFE57373),
        error = Color(0xFFFF1744),
        success = Color(0xFF69F0AE)
    ),
    TerminalThemeConfig(
        id = "toxic_hazard",
        name = "Toxic Hazard",
        description = "Acid bioluminescent fallout radar",
        price = 450,
        primary = Color(0xFF39FF14),
        primaryDim = Color(0x3339FF14),
        secondary = Color(0xFFBF00FF),
        tertiary = Color(0xFF00E5FF),
        bgDark = Color(0xFF0A0512),
        surface1 = Color(0xFF140C22),
        surface2 = Color(0xFF201534),
        surface3 = Color(0xFF2F204B),
        textLight = Color(0xFFF3E5F5),
        textGray = Color(0xFFBA68C8),
        error = Color(0xFFFF1744),
        success = Color(0xFF39FF14)
    ),
    TerminalThemeConfig(
        id = "sunset_strip",
        name = "Sunset Wasteland",
        description = "Synthwave retro-futuristic horizon",
        price = 500,
        primary = Color(0xFFFF6B35),
        primaryDim = Color(0x33FF6B35),
        secondary = Color(0xFF00E5FF),
        tertiary = Color(0xFFFFD166),
        bgDark = Color(0xFF0E0916),
        surface1 = Color(0xFF1A1226),
        surface2 = Color(0xFF281D39),
        surface3 = Color(0xFF392B4E),
        textLight = Color(0xFFFFF0F5),
        textGray = Color(0xFFCE93D8),
        error = Color(0xFFFF4081),
        success = Color(0xFF00E676)
    )
)

fun getTerminalTheme(id: String): TerminalThemeConfig {
    return ThemeList.find { it.id == id } ?: ThemeList.first()
}
